var WGlobalCompositeOperationType = {
    'SOURCE-OVER': 'source-over',
    'SOURCE-IN': 'source-in',
    'SOURCE-OUT': 'source-out',
    'SOURCE-ATOP': 'source-atop',
    'DESTINATION-OVER': 'destination-over',
    'DESTINATION-IN': 'destination-in',
    'DESTINATION-OUT': 'destination-out',
    'DESTINATION-ATOP': 'destination-atop',
    'LIGHTER': 'lighter',
    'COPY': 'copy',
    'XOR': 'xor',
    'MULTIPLY': 'multiply',
    'SCREEN': 'screen',
    'OVERLAY': 'overlay',
    'DARKEN': 'darken',
    'LIGHTEN': 'lighten',
    'COLOR-DODGE': 'color-dodge',
    'COLOR-BURN': 'color-burn',
    'HARD-LIGHT': 'hard-light',
    'SOFT-LIGHT': 'soft-light',
    'DIFFERENCE': 'difference',
    'EXCLUSION': 'exclusion',
    'HUE': 'hue',
    'SATURATION': 'saturation',
    'COLOR': 'color',
    'LUMINOSITY': 'luminosity'
}

export default WGlobalCompositeOperationType